services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: rdalmau
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rafelcod@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
